
version: "3"

tasks:
  sso:
    aliases:
      - gen
    desc: "Generate gRPC code from proto files"
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  notification:
    aliases:
      - gen
    desc: "Generate gRPC code from proto files"
    cmds:
      - protoc -I proto proto/notification/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative